# Generated by Django 4.1.1 on 2023-03-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonteacherapp', '0001_initial'),
    ]

    operations = [
    ]
