# Generated by Django 4.1.1 on 2023-03-17 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonteacherapp', '0002_auto_20230317_0833'),
    ]

    operations = [
    ]
