# Generated by Django 4.1.1 on 2023-03-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonteacherapp', '0004_user_test_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('explanation', models.CharField(max_length=256)),
                ('answer_A', models.CharField(max_length=100)),
                ('answer_B', models.CharField(max_length=100)),
                ('answer_C', models.CharField(max_length=100)),
                ('answer_D', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pre_test',
            },
        ),
    ]
