# Generated by Django 4.1.1 on 2023-05-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonteacherapp', '0005_pretest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assignment_level',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='assignment_progress_level',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='chapter_level',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
