# Generated by Django 4.1.1 on 2023-06-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonteacherapp', '0006_user_assignment_level_user_assignment_progress_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('assignment_progress_level', models.CharField(max_length=200)),
                ('assignment_level', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('time', models.TextField()),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonteacherapp.user')),
            ],
        ),
    ]
