# Generated by Django 5.0.6 on 2024-06-13 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonteacherapp', '0007_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='user_id',
            new_name='message',
        ),
    ]
